### ISSUE TITLE
使用pip install -r requirements.txt 提示  Could not find a version that satisfies the requirement torch==1.13.1

### ISSUE THREAD

**Issue by dark-hxx** [tkgs0/Momoko#1]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/Momoko/issues) 中没有相同或相似的问题。

### Momoko

master最新提交

### go-cqhttp

代码拉下来没有修改

### nonebot

代码拉下来没有修改

### Python

Python 3.10.9

### 操作系统

win11 22H2

### 列出安装的 Python 包

D:\github\Momoko>pip freeze -l

D:\github\Momoko>

### 问题描述

执行pip install -r requirements.txt时候 显示：
`ERROR: Could not find a version that satisfies the requirement torch==1.13.1 (from versions: none)
ERROR: No matching distribution found for torch==1.13.1`

### 复现步骤

1.安装python环境 添加 path路径
2.执行ERROR: Could not find a version that satisfies the requirement torch==1.13.1 (from versions: none)
ERROR: No matching distribution found for torch==1.13.1

### 实际行为

ERROR: Could not find a version that satisfies the requirement torch==1.13.1 (from versions: none)
ERROR: No matching distribution found for torch==1.13.1

### 日志信息

D:\github\Momoko>pip install -r requirements.txt
Collecting nb-cli>=1.0.0 (from -r requirements.txt (line 1))
  Using cached nb_cli-1.1.2-py3-none-any.whl (57 kB)
Collecting nonebot2[fastapi]>=2.0.0rc2 (from -r requirements.txt (line 2))
  Using cached nonebot2-2.0.0rc4-py3-none-any.whl (94 kB)
Collecting nonebot-adapter-onebot>=2.2.0 (from -r requirements.txt (line 3))
  Using cached nonebot_adapter_onebot-2.2.2-py3-none-any.whl (47 kB)
Collecting nonebot-plugin-apscheduler>=0.2.0 (from -r requirements.txt (line 4))
  Using cached nonebot_plugin_apscheduler-0.2.0-py3-none-any.whl (3.9 kB)
Collecting nonebot-plugin-imageutils>=0.1.13 (from -r requirements.txt (line 5))
  Using cached nonebot_plugin_imageutils-0.1.17-py3-none-any.whl (17 kB)
Collecting nonebot-plugin-guild-patch>=0.2.0 (from -r requirements.txt (line 6))
  Using cached nonebot_plugin_guild_patch-0.2.3-py3-none-any.whl (7.4 kB)
Collecting aiofiles>=22.1.0 (from -r requirements.txt (line 7))
  Using cached aiofiles-23.1.0-py3-none-any.whl (14 kB)
Collecting aiohttp[speedups]>=3.8.3 (from -r requirements.txt (line 8))
  Using cached aiohttp-3.8.4-cp39-cp39-win32.whl (307 kB)
Collecting cachetools>=5.0.0 (from -r requirements.txt (line 9))
  Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting deep-translator>=1.8.0 (from -r requirements.txt (line 10))
  Using cached deep_translator-1.10.1-py3-none-any.whl (35 kB)
Collecting diskcache>=5.4.0 (from -r requirements.txt (line 11))
  Using cached diskcache-5.5.1-py3-none-any.whl (45 kB)
Collecting emoji>=2.0.0 (from -r requirements.txt (line 12))
  Using cached emoji-2.2.0.tar.gz (240 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting feedparser>=6.0.3 (from -r requirements.txt (line 13))
  Using cached feedparser-6.0.10-py3-none-any.whl (81 kB)
Collecting imagehash>=4.3.0 (from -r requirements.txt (line 14))
  Using cached ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
Collecting langid>=1.1.6 (from -r requirements.txt (line 15))
  Using cached langid-1.1.6.tar.gz (1.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting magneturi>=1.3 (from -r requirements.txt (line 16))
  Using cached magneturi-1.3.tar.gz (5.5 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting picimagesearch>=3.7.0 (from -r requirements.txt (line 17))
  Using cached picimagesearch-3.9.0-py3-none-any.whl (22 kB)
Collecting pikpakapi>=0.0.1 (from -r requirements.txt (line 18))
  Using cached pikpakapi-0.1.1-py3-none-any.whl (5.5 kB)
Collecting psutil>=5.9.0 (from -r requirements.txt (line 19))
  Using cached psutil-5.9.5-cp36-abi3-win32.whl (249 kB)
Collecting pydub>=0.25.1 (from -r requirements.txt (line 20))
  Using cached pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Collecting python-qbittorrent>=0.4.1 (from -r requirements.txt (line 21))
  Using cached python_qbittorrent-0.4.3-py3-none-any.whl (9.8 kB)
Collecting shelved-cache>=0.3.1 (from -r requirements.txt (line 22))
  Using cached shelved_cache-0.3.1-py3-none-any.whl (7.8 kB)
Collecting tenacity>=8.0.0 (from -r requirements.txt (line 23))
  Using cached tenacity-8.2.2-py3-none-any.whl (24 kB)
Collecting tinydb>=4.6.0 (from -r requirements.txt (line 24))
  Using cached tinydb-4.7.1-py3-none-any.whl (24 kB)
Collecting ujson>=5.2.0 (from -r requirements.txt (line 25))
  Using cached ujson-5.7.0-cp39-cp39-win32.whl (38 kB)
Collecting arrow>=1.2.3 (from -r requirements.txt (line 26))
  Using cached arrow-1.2.3-py3-none-any.whl (66 kB)
Collecting dbutils>=3.0.2 (from -r requirements.txt (line 27))
  Using cached DBUtils-3.0.2-py3-none-any.whl (32 kB)
Collecting mockingbirdforuse (from -r requirements.txt (line 29))
  Using cached MockingBirdForUse-0.2.3-py3-none-any.whl (46 kB)
ERROR: Could not find a version that satisfies the requirement torch==1.13.1 (from versions: none)
ERROR: No matching distribution found for torch==1.13.1

**Comment by tkgs0** [comment]
pypi官方源里有1.13.1版本的torch, 建议换个源试试  
  
据日志显示你所使用的环境是python 3.9, 而非python 3.10.9, 当然这可能不是导致问题的原因 (torch 1.13.1 支持 3.9 和 3.10)  
  
torch与numpy版本不匹配可能会造成不可预料的问题, 如果你想要安装其他版本的torch, 你可能需要自己寻找与之兼容的numpy版本  
  
p.s. 如果你所使用的是32位的Windows, 部分依赖可能不支持

**Comment by tkgs0** [comment]
已移除插件 `mockingbird`, 已从 `pyproject.toml` `requirements.txt` 移除非必要依赖, 该issue关闭
