### ISSUE TITLE
 连接到反向WebSocket Universal服务器 ws://127.0.0.1:6677/onebot/v11/ws 时出现错误: websocket: bad handshake     [WARNING] nonebot | OneBot V11 | Missing Authorization Header

### ISSUE THREAD

**Issue by fatekingsama** [tkgs0/Momoko#2]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/Momoko/issues) 中没有相同或相似的问题。

### Momoko

最新版

### go-cqhttp

最新版

### nonebot

默认

### Python

3.10.0

### 操作系统

centos

### 列出安装的 Python 包

aiodns==3.0.0
aiofiles==23.2.1
aiohttp==3.8.5
aiosignal==1.3.1
anyio==3.7.1
APScheduler==3.10.4
arrow==1.2.3
async-timeout==4.0.3
attrs==23.1.0
audioread==3.0.0
bbcode==1.1.0
beautifulsoup4==4.12.2
binaryornot==0.4.4
Brotli==1.0.9
cachetools==5.3.1
cashews==6.2.0
certifi==2023.7.22
cffi==1.15.1
chardet==5.2.0
charset-normalizer==3.2.0
click==8.1.7
contourpy==1.1.0
cookiecutter==2.3.0
cssselect==1.2.0
cycler==0.11.0
DBUtils==3.0.3
decorator==5.1.1
deep-translator==1.11.4
diskcache==5.6.3
distlib==0.3.7
emoji==2.8.0
exceptiongroup==1.1.3
fastapi==0.103.0
feedparser==6.0.10
filelock==3.12.3
fonttools==4.42.1
frozenlist==1.4.0
h11==0.14.0
httpcore==0.17.3
httptools==0.6.0
httpx==0.24.1
idna==3.4
ImageHash==4.3.1
inflect==5.6.2
Jinja2==3.1.2
joblib==1.3.2
kiwisolver==1.4.5
langid==1.1.6
librosa==0.9.2
llvmlite==0.40.1
loguru==0.6.0
lxml==4.9.3
magneturi==1.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mockingbirdforuse==0.1.0
msgpack==1.0.5
multidict==6.0.4
nb-cli==1.2.3
nonebot-adapter-onebot==2.2.4
nonebot-plugin-apscheduler==0.3.0
nonebot-plugin-guild-patch==0.2.3
nonebot-plugin-imageutils==0.1.17
nonebot2==2.0.1
noneprompt==0.1.9
numba==0.57.1
numpy==1.23.5
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
opencv-python-headless==4.8.0.76
packaging==23.1
picimagesearch==3.9.5
pikpakapi==0.1.3
Pillow==9.5.0
platformdirs==2.6.2
pooch==1.7.0
prompt-toolkit==3.0.39
psutil==5.9.5
pycares==4.3.0
pycparser==2.21
pydantic==1.10.12
pydub==0.25.1
pyfiglet==0.8.post1
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pypinyin==0.46.0
pyquery==2.0.0
python-dateutil==2.8.2
python-dotenv==1.0.0
python-qbittorrent==0.4.3
python-slugify==8.0.1
pytz==2023.3
PyWavelets==1.4.1
PyYAML==6.0.1
requests==2.31.0
resampy==0.4.2
rich==13.5.2
scikit-learn==1.3.0
scipy==1.11.2
sgmllib3k==1.0.0
shelved-cache==0.3.1
six==1.16.0
sniffio==1.3.0
soundfile==0.12.1
soupsieve==2.5
starlette==0.27.0
tenacity==8.2.3
tencentcloud-sdk-python==3.0.973
text-unidecode==1.3
threadpoolctl==3.2.0
tinydb==4.8.0
tomli==2.0.1
tomlkit==0.12.1
torch @ file:///workspace/python/Momoko/torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl#sha256=fd12043868a34a8da7d490bf6db66991108b00ffbeecb034228bfcbbd4197143
typing_extensions==4.7.1
tzlocal==5.0.1
ujson==5.8.0
Unidecode==1.3.6
urllib3==2.0.4
uvicorn==0.23.2
uvloop==0.17.0
virtualenv==20.17.1
watchfiles==0.20.0
wcwidth==0.2.6
webrtcvad==2.0.10
websockets==11.0.3
yarl==1.9.2

### 问题描述

 go-cqhttp报错
连接到反向WebSocket Universal服务器 ws://127.0.0.1:6677/onebot/v11/ws 时出现错误: websocket: bad handshake
项目报错
09-03 12:25:35 [WARNING] nonebot | OneBot V11 | Missing Authorization Header
09-03 12:25:35 [INFO] uvicorn | ('127.0.0.1', 38812) - "WebSocket /onebot/v11/ws" 403
09-03 12:25:35 [INFO] websockets | connection failed (403 Forbidden)
09-03 12:25:35 [INFO] websockets | connection closed

### 复现步骤

1.启动项目
2.启动 go-cqhttp
3.两边开始报错

### 实际行为

 go-cqhttp报错
连接到反向WebSocket Universal服务器 ws://127.0.0.1:6677/onebot/v11/ws 时出现错误: websocket: bad handshake
项目报错
09-03 12:25:35 [WARNING] nonebot | OneBot V11 | Missing Authorization Header
09-03 12:25:35 [INFO] uvicorn | ('127.0.0.1', 38812) - "WebSocket /onebot/v11/ws" 403
09-03 12:25:35 [INFO] websockets | connection failed (403 Forbidden)
09-03 12:25:35 [INFO] websockets | connection closed

### 日志信息

 go-cqhttp报错
连接到反向WebSocket Universal服务器 ws://127.0.0.1:6677/onebot/v11/ws 时出现错误: websocket: bad handshake
项目报错
09-03 12:25:35 [WARNING] nonebot | OneBot V11 | Missing Authorization Header
09-03 12:25:35 [INFO] uvicorn | ('127.0.0.1', 38812) - "WebSocket /onebot/v11/ws" 403
09-03 12:25:35 [INFO] websockets | connection failed (403 Forbidden)
09-03 12:25:35 [INFO] websockets | connection closed

**Comment by tkgs0** [comment]
抱歉更新时忘记删了, 修改机器人目录下 **.env** 文件, 将以下字段删除:  
`ONEBOT_ACCESS_TOKEN="KEJWwj5N5pqwSQBbgrxKCX3eaC63Zjxr"`
